# Generated by Django 5.1.3 on 2024-11-19 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Management_App', '0002_rename_customuser_user'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
