# Generated by Django 5.1.3 on 2024-11-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Management_App', '0004_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
