# Generated by Django 5.1.3 on 2024-11-20 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Management_App', '0005_remove_task_assigned_to_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
