# Generated by Django 5.1.3 on 2024-11-25 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Management_App', '0006_task_assignto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
